### PR TITLE
Add template-haskell-optics example

### PR DESCRIPTION
**Pull request by ysangkok**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks!

**Comment by tomjaguarpaw** [comment]
Tangentially, here, to  minimize the amount of CPP, I might suggest defining

```haskell
#if MIN_VERSION_template_haskell(2,21,0)
type BndrArg = ()
#else
type BndrArg = BndrVis
#endif
```

and then just using `TyVarBndr BndrArg` everywhere, instead of CPP everywhere.

**Comment by ysangkok** [comment]
I think that `#if` is the wrong way around, most of these use `BndrVis` in from th-2.21. Good suggestion but I don't wanna send another PR. Focusing on `swagger2` now.

**Comment by ysangkok** [comment]
I do wonder if the change in `_DataInstD` is really necessary, because it seems to be two ways of writing the same thing. Weird.

**Comment by tomjaguarpaw** [comment]
> I think that #if is the wrong way around

Ah right

> Good suggestion but I don't wanna send another PR. 

Fair enough

**Pull request merged**
